name: Build petsc4py docs
on: [push]

jobs:
  build:
    name: "Build Firedrake"
    # The type of runner that the job will run on
    runs-on: firedrakeproject/firedrake-env:latest

    steps:
      - uses: actions/checkout@v3
      - name: configure
        run: ./configure




